### ISSUE TITLE
Error: Class 'humhub\modules\directory\widgets\Menu' not found in

### ISSUE THREAD

**Issue by Deister82** [KeudellCoding/HumHub-Modules-UserMap#11] opened 2022-05-15 22:46 UTC
Same Error by Installation over Admin Store.
Log:
```
Error: Class 'humhub\modules\directory\widgets\Menu' not found in /..../protected/modules/humdav/config.php:23
Stack trace:
#0 /..../protected/humhub/components/bootstrap/ModuleAutoLoader.php(77): include()
#1 /..../protected/humhub/components/bootstrap/ModuleAutoLoader.php(48): humhub\components\bootstrap\ModuleAutoLoader::findModules(Array)
#2 //..../protected/humhub/components/bootstrap/ModuleAutoLoader.php(34): humhub\components\bootstrap\ModuleAutoLoader::locateModules()
#3 /..../protected/vendor/yiisoft/yii2/base/Application.php(325): humhub\components\bootstrap\ModuleAutoLoader->bootstrap(Object(humhub\components\console\Application))
#4 /..../protected/vendor/yiisoft/yii2/base/Application.php(271): yii\base\Application->bootstrap()
#5 /..../protected/vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init()
#6 /..../protected/humhub/components/console/Application.php(90): yii\console\Application->init()
#7 /..../protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\components\console\Application->init()
#8 /..../protected/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#9/..../protected/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#10 /..../protected/humhub/components/console/Application.php(52): yii\console\Application->__construct(Array)
#11 /..../protected/yii(28): humhub\components\console\Application->__construct(Array)
#12 {main} 
```

**Comment by KarlKeu00** [comment] 2022-05-16 08:38
Duplicate of #9

**Closed as completed by KarlKeu00** 2022-05-16 08:38 UTC
